plugins {
  id 'java'
}

group = 'com.example'
version = '1.0.0-SNAPSHOT'

def karateVersion = '1.4.1'

test {
  useTestNG()
  systemProperty 'karate.options', '--tags ~@ignore'
}

repositories {
  mavenCentral()
}

dependencies {
  testImplementation "com.intuit.karate:karate-testng:${karateVersion}"
  testImplementation 'org.testng:testng:7.10.2'
}

java {
  sourceCompatibility = JavaVersion.VERSION_11
  targetCompatibility = JavaVersion.VERSION_11
}
